# Extract data

In [1]:
! pip install kaggle --quiet
! mkdir ~/.kaggle
! cp /content/drive/MyDrive/kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle competitions download -c m5-forecasting-accuracy
! unzip /content/m5-forecasting-accuracy.zip

Downloading m5-forecasting-accuracy.zip to /content
  0% 0.00/45.8M [00:00<?, ?B/s]
100% 45.8M/45.8M [00:00<00:00, 1.16GB/s]
Archive:  /content/m5-forecasting-accuracy.zip
  inflating: calendar.csv
  inflating: sales_train_evaluation.csv
  inflating: sales_train_validation.csv
  inflating: sample_submission.csv
  inflating: sell_prices.csv

# Accessing Data

## sales data

In [33]:
import pandas as pd
import numpy as np

In [74]:
sales_df = pd.read_csv('/content/sales_train_validation.csv')
sales_df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [75]:
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                  df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df

In [76]:
sales_df = reduce_mem_usage(sales_df)

Mem. usage decreased to 95.00 Mb (78.7% reduction)

In [77]:
sales_df = sales_df[(sales_df['cat_id']=='FOODS') & (sales_df['dept_id']=='FOODS_1')]

In [78]:
id_vars = ['id', 'item_id', 'dept_id', 'cat_id','store_id', 'state_id']
sales_long = pd.melt(sales_df, id_vars=id_vars, var_name='day', value_name='demand')
sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,day,demand
0,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1,3
1,FOODS_1_002_CA_1_validation,FOODS_1_002,FOODS_1,FOODS,CA_1,CA,d_1,0
2,FOODS_1_003_CA_1_validation,FOODS_1_003,FOODS_1,FOODS,CA_1,CA,d_1,0
3,FOODS_1_004_CA_1_validation,FOODS_1_004,FOODS_1,FOODS,CA_1,CA,d_1,0
4,FOODS_1_005_CA_1_validation,FOODS_1_005,FOODS_1,FOODS,CA_1,CA,d_1,3

In [79]:
zero_counts = sales_long.groupby('item_id')['demand'].apply(lambda x: (x == 0).sum()).reset_index()
food_items = zero_counts.sort_values('demand')['item_id'].tolist()
food_items[:3]

['FOODS_1_085', 'FOODS_1_218', 'FOODS_1_018']

In [80]:
filtered_df = sales_long[sales_long['item_id'].isin(food_items[:3])]
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57390 entries, 16 to 4132078
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        57390 non-null  object
 1   item_id   57390 non-null  object
 2   dept_id   57390 non-null  object
 3   cat_id    57390 non-null  object
 4   store_id  57390 non-null  object
 5   state_id  57390 non-null  object
 6   day       57390 non-null  object
 7   demand    57390 non-null  int16
dtypes: int16(1), object(7)
memory usage: 3.6+ MB

In [81]:
filtered_df.drop(['cat_id', 'dept_id'], axis=1, inplace=True)
filtered_df.head()

/tmp/ipython-input-81-2549727365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(['cat_id', 'dept_id'], axis=1, inplace=True)

                              id      item_id store_id state_id  day  demand
16   FOODS_1_018_CA_1_validation  FOODS_1_018     CA_1       CA  d_1      17
83   FOODS_1_085_CA_1_validation  FOODS_1_085     CA_1       CA  d_1      10
214  FOODS_1_218_CA_1_validation  FOODS_1_218     CA_1       CA  d_1      10
232  FOODS_1_018_CA_2_validation  FOODS_1_018     CA_2       CA  d_1       4
299  FOODS_1_085_CA_2_validation  FOODS_1_085     CA_2       CA  d_1       4

## calender data

In [82]:
calender_df = pd.read_csv('/content/calendar.csv')
calender_df = reduce_mem_usage(calender_df)
calender_df.head()

Mem. usage decreased to  0.12 Mb (41.9% reduction)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [83]:
calender_df['is_holiday'] = np.where(
    calender_df['event_name_1'].notna() | calender_df['event_name_2'].notna(), 1, 0)

In [84]:
calender_df.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,is_holiday
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1,0

In [85]:
calender_df.drop(['event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',	'weekday'	,'wday', 'snap_CA',	'snap_TX',	'snap_WI'], axis=1, inplace=True)
calender_df.rename(columns={'d': 'day'}, inplace=True)

In [86]:
data = pd.merge(filtered_df, calender_df, how = 'left', on = ['day'])
data.head()

,id,item_id,store_id,state_id,day,demand,date,wm_yr_wk,month,year,is_holiday
0,FOODS_1_018_CA_1_validation,FOODS_1_018,CA_1,CA,d_1,17,2011-01-29,11101,1,2011,0
1,FOODS_1_085_CA_1_validation,FOODS_1_085,CA_1,CA,d_1,10,2011-01-29,11101,1,2011,0
2,FOODS_1_218_CA_1_validation,FOODS_1_218,CA_1,CA,d_1,10,2011-01-29,11101,1,2011,0
3,FOODS_1_018_CA_2_validation,FOODS_1_018,CA_2,CA,d_1,4,2011-01-29,11101,1,2011,0
4,FOODS_1_085_CA_2_validation,FOODS_1_085,CA_2,CA,d_1,4,2011-01-29,11101,1,2011,0

## price data

In [87]:
sell_price_df = pd.read_csv('/content/sell_prices.csv')
sell_price_df = reduce_mem_usage(sell_price_df)
sell_price_df.head()

Mem. usage decreased to 130.48 Mb (37.5% reduction)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325    9.578125
1     CA_1  HOBBIES_1_001     11326    9.578125
2     CA_1  HOBBIES_1_001     11327    8.257812
3     CA_1  HOBBIES_1_001     11328    8.257812
4     CA_1  HOBBIES_1_001     11329    8.257812

In [88]:
data = data.merge(sell_price_df, on=['store_id', 'item_id', 'wm_yr_wk'], how='left')

In [65]:
data.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,id,item_id,store_id,state_id,day,demand,date,wm_yr_wk,month,year,is_holiday,sell_price
0,FOODS_1_018_CA_1_validation,FOODS_1_018,CA_1,CA,d_1,17,2011-01-29,11101,1,2011,0,1.0
1,FOODS_1_085_CA_1_validation,FOODS_1_085,CA_1,CA,d_1,10,2011-01-29,11101,1,2011,0,1.0
2,FOODS_1_218_CA_1_validation,FOODS_1_218,CA_1,CA,d_1,10,2011-01-29,11101,1,2011,0,1.0
3,FOODS_1_018_CA_2_validation,FOODS_1_018,CA_2,CA,d_1,4,2011-01-29,11101,1,2011,0,1.0
4,FOODS_1_085_CA_2_validation,FOODS_1_085,CA_2,CA,d_1,4,2011-01-29,11101,1,2011,0,1.0

In [89]:
data.isnull().sum()

id            0
item_id       0
store_id      0
state_id      0
day           0
demand        0
date          0
wm_yr_wk      0
month         0
year          0
is_holiday    0
sell_price    0
dtype: int64

In [90]:
data.drop(columns=['id', 'day', 'wm_yr_wk'], inplace=True)

In [91]:
data.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,item_id,store_id,state_id,demand,date,month,year,is_holiday,sell_price
0,FOODS_1_018,CA_1,CA,17,2011-01-29,1,2011,0,1.0
1,FOODS_1_085,CA_1,CA,10,2011-01-29,1,2011,0,1.0
2,FOODS_1_218,CA_1,CA,10,2011-01-29,1,2011,0,1.0
3,FOODS_1_018,CA_2,CA,4,2011-01-29,1,2011,0,1.0
4,FOODS_1_085,CA_2,CA,4,2011-01-29,1,2011,0,1.0

In [92]:
data['date'] = pd.to_datetime(data['date'])

In [93]:
data.to_csv('data.csv', index=False)